-- Ejecutar en Supabase SQL Editor
CREATE TYPE user_role AS ENUM ('admin','gestor','coordinador','asesor','docente');
CREATE TABLE centros (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), nombre TEXT NOT NULL, codigo TEXT, direccion TEXT, localidad TEXT, created_at TIMESTAMPTZ DEFAULT now());
CREATE TABLE cursos_escolares (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), nombre TEXT NOT NULL, anio_inicio INT, anio_fin INT, activo BOOLEAN DEFAULT true, created_at TIMESTAMPTZ DEFAULT now());
CREATE TABLE usuarios (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), auth_id UUID REFERENCES auth.users(id) ON DELETE CASCADE, nombre_completo TEXT, email TEXT UNIQUE NOT NULL, nombre_usuario TEXT UNIQUE, rol user_role NOT NULL DEFAULT 'docente', centro_id UUID REFERENCES centros(id), activo BOOLEAN DEFAULT true, primer_acceso BOOLEAN DEFAULT true, created_at TIMESTAMPTZ DEFAULT now());
CREATE TABLE alumnos (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), nombre TEXT NOT NULL, apellido1 TEXT NOT NULL, apellido2 TEXT, centro_id UUID REFERENCES centros(id), curso_id UUID REFERENCES cursos_escolares(id), activo BOOLEAN DEFAULT true, created_at TIMESTAMPTZ DEFAULT now());
CREATE TABLE docente_alumno (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), docente_id UUID REFERENCES usuarios(id) ON DELETE CASCADE, alumno_id UUID REFERENCES alumnos(id) ON DELETE CASCADE, created_at TIMESTAMPTZ DEFAULT now(), UNIQUE(docente_id,alumno_id));
CREATE TABLE horarios (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), docente_id UUID REFERENCES usuarios(id) ON DELETE CASCADE, alumno_id UUID REFERENCES alumnos(id) ON DELETE CASCADE, dia_semana INT CHECK (dia_semana BETWEEN 1 AND 7), hora_inicio TIME, hora_fin TIME, created_at TIMESTAMPTZ DEFAULT now());
CREATE TABLE registro_diario (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), docente_id UUID REFERENCES usuarios(id) ON DELETE CASCADE, alumno_id UUID REFERENCES alumnos(id) ON DELETE CASCADE, fecha DATE NOT NULL DEFAULT CURRENT_DATE, asistencia TEXT CHECK (asistencia IN ('presente','ausente','justificado')) DEFAULT 'presente', observaciones TEXT, created_at TIMESTAMPTZ DEFAULT now(), UNIQUE(docente_id,alumno_id,fecha));
CREATE TABLE asesor_centros (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), asesor_id UUID REFERENCES usuarios(id) ON DELETE CASCADE, centro_id UUID REFERENCES centros(id) ON DELETE CASCADE, created_at TIMESTAMPTZ DEFAULT now(), UNIQUE(asesor_id,centro_id));
CREATE OR REPLACE FUNCTION get_my_role() RETURNS user_role AS $$ SELECT rol FROM usuarios WHERE auth_id = auth.uid() $$ LANGUAGE sql SECURITY DEFINER;